---
- name: "Installing apache webserver"
  hosts: amazon
  become: true
  vars_files:
    - variables.yml
  tasks:
    
    - name: "Installing apache webserver"
      yum:
        name: httpd
        state: present

    - name: "installing php support"
      yum:
        name: php
        state: present

    - name: "Creating httpd.conf from httpd.conf.tmpl"
      template: 
        src: httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf

    - name: "Creating vhost from virtualhost.conf.tmpl"
      template: 
        src: virtualhost.conf.tmpl
        dest: /etc/httpd/conf.d/default.conf
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}"

    - name: "Creating docroot {{doc_root}}"
      file:
        path: "{{doc_root}}"
        state: directory    
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}"
    
    - name: "Creating test files inside doc root"
      copy:
        src: "{{item}}"
        dest: "/var/www/html/{{httpd_hostname}}"
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}"
      with_items:
        - test.html
        - test.php
            
    - name: "Restarting/enabling httpd"
      service:
        name: httpd
        state: restarted
        enabled: true
